
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: coderschool.vn

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
    CA:
      Hostname: ca


# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Fredrick
    Domain: fredrick.coderschool.vn
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
    CA:
      Hostname: ca

  # ---------------------------------------------------------------------------
  # Org2: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Alice
    Domain: alice.coderschool.vn
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
    CA:
      Hostname: ca

  - Name: Bob
    Domain: bob.coderschool.vn
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1
    CA:
      Hostname: ca
